[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "aoc01",
    "aoc02",
    "aoc03",
    "aoc04",
    "aoc05",
    "aoc06",
    "aoc07",
    "aoc08",
    "aoc09",
]
